import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Sidebar } from "@/components/organism/sidebar"
import { SidebarProvider } from "@/components/ui/sidebar"
import MainLayout from "@/components/templates/main-layout"

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Chick-Fil-A",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <SidebarProvider>
          <Sidebar />
          <MainLayout>{children}</MainLayout>
        </SidebarProvider>
      </body>
    </html>
  )
}
